export const TOKEN_CONFIG = {
  MAX_CONTEXT_TOKENS: 150_000,
  CONTEXT_MANAGEMENT_THRESHOLD: 0.7,
  KEEP_RECENT_MESSAGES: 8,
  SUMMARY_MAX_OUTPUT_TOKENS: 15_000,
  CHARS_PER_TOKEN: 3.5,
  TOOL_CALL_OVERHEAD: 50,
  TOOL_SCHEMA_OVERHEAD: 1050,
} as const;
