export const TOKEN_CONFIG = {
  MAX_CONTEXT_TOKENS: 150_000,
  CONTEXT_MANAGEMENT_THRESHOLD: 0.7,
  KEEP_RECENT_MESSAGES: 8,
  SUMMARY_MAX_OUTPUT_TOKENS: 15_000,
  CHARS_PER_TOKEN: 4,
  TOOL_CALL_OVERHEAD: 40,
  TOOL_SCHEMA_OVERHEAD: 450,
} as const;
